#!/bin/zsh
# Command to automatically create Pull Requests on Github

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Check if current branch has been pushed to git remote
git ls-remote --exit-code --heads $(git remote get-url --push origin) $BRANCH_NAME

if [[ "$?" == "2" ]]; then 
    echo "Branch does not on remote"; 
    git push -u origin HEAD --no-verify
fi

echo "Committing and pushing all change…"
git add --all . && git commit -m "$BRANCH_NAME Auto-commit" && git push -u origin HEAD

gh pr create --fill --assignee @me
