#!/bin/sh

# Open all pull requests that references a commit hash in default browser
# Usage: git-pr <SHA-1>

REPO=${2:-ajw998}
GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

response=$(curl -sbS -o -i /dev/null "Content-Type: application/json" -u $GH_USERNAME:$GH_TOKEN "https://api.github.com/search/issues?q=$1+type%3Apr+is%3Amerged+repo%3A${REPO}%2F${PWD##*/}&sort=created&order=desc")

output=$(jq -r ".items[] | {html_url} | select(.html_url != null) | values[]" <<< "${response}")

 for i in $output
 do
   printf "Opening ${GREEN}%s \n${NORMAL}" "$i"
   open $i
 done
